import { readdirSync, existsSync, writeFileSync, mkdirSync, rmSync, readFileSync, cpSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';
import { BaseAdapter } from './base.js';

export class CopilotAdapter extends BaseAdapter {
  get toolName() { return 'copilot'; }

  getUserDir() { return join(homedir(), '.copilot'); }

  getSkillsDir() { return join(this.getUserDir(), 'skills'); }

  getCommandsDir() { return join(this.getUserDir(), 'instructions'); }

  get capabilities() {
    return { hooks: false, skills: true, commands: true, plugin: false, mcpConfig: false, globalInstructions: true, templates: true };
  }

  install(loomRoot, version, projectRoot = null) {
    const log = [];
    log.push(`Installing loom@${version} → ${this.toolName} (user-level)`);
    this._copySkills(loomRoot, log);
    this._copyTemplates(loomRoot, log);
    this._copyCommands(loomRoot, log);
    this._postInstall(loomRoot, version, log, projectRoot);
    return log;
  }

  uninstall(loomRootOrProjectRoot = null, projectRoot = null) {
    const repositoryRoot = projectRoot ?? loomRootOrProjectRoot;
    const log = [];
    log.push(`Uninstalling loom → ${this.toolName} (user-level)`);
    this._removeSkills(log);
    this._removeTemplates(log);
    this._removeCommands(log);
    this._removeGlobalInstructions(log);
    this._removeRepositoryInstructions(repositoryRoot, log);
    this._removeSetupSteps(repositoryRoot, log);
    this._removeVerificationWorkflow(repositoryRoot, log);
    return log;
  }

  _copyTemplates(loomRoot, log) {
    const src = join(loomRoot, 'templates');
    if (!existsSync(src)) return;

    const initProjectDir = join(this.getSkillsDir(), 'loom-init-project');
    if (!existsSync(initProjectDir)) {
      log.push('  templates: loom-init-project skill not found, skipped');
      return;
    }

    const dest = join(initProjectDir, 'templates');
    mkdirSync(dest, { recursive: true });
    cpSync(src, dest, { recursive: true, force: true });
    log.push('  templates: copied to loom-init-project skill dir');
  }

  _removeTemplates(log) {
    const initProjectDir = join(this.getSkillsDir(), 'loom-init-project', 'templates');
    if (existsSync(initProjectDir)) {
      rmSync(initProjectDir, { recursive: true, force: true });
      log.push('  templates: removed from loom-init-project skill dir');
    }
  }

  _removeGlobalInstructions(log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (!existsSync(instructionsPath)) return;
    try {
      const content = readFileSync(instructionsPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  copilot-instructions.md — not generated by loom, skipped');
        return;
      }
      rmSync(instructionsPath, { force: true });
      log.push('  copilot-instructions.md removed');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _postInstall(loomRoot, version, log, projectRoot = null) {
    this._ensureGlobalInstructions(loomRoot, version, log);
    this._ensureRepositoryInstructions(loomRoot, version, projectRoot, log);
    this._ensureSetupSteps(projectRoot, log);
    this._ensureVerificationWorkflow(projectRoot, log);
  }

  _ensureGlobalInstructions(loomRoot, version, log) {
    const instructionsPath = join(this.getUserDir(), 'copilot-instructions.md');
    if (existsSync(instructionsPath)) {
      log.push('  copilot-instructions.md already exists, skipping');
      return;
    }

    const content = this._buildInstructionsContent(loomRoot, version, '~/.copilot/skills/');
    try {
      writeFileSync(instructionsPath, content, 'utf-8');
      log.push('  copilot-instructions.md written');
    } catch (e) {
      log.push(`  copilot-instructions.md: ${e.message}`);
    }
  }

  _ensureRepositoryInstructions(loomRoot, version, projectRoot, log) {
    if (!projectRoot) return;
    const instructionsPath = join(projectRoot, '.github', 'copilot-instructions.md');
    if (existsSync(instructionsPath)) {
      log.push('  repository copilot-instructions.md already exists, skipping');
      return;
    }

    const content = this._buildInstructionsContent(loomRoot, version, '~/.copilot/skills/');
    try {
      mkdirSync(dirname(instructionsPath), { recursive: true });
      writeFileSync(instructionsPath, content, 'utf-8');
      log.push('  repository copilot-instructions.md written');
    } catch (e) {
      log.push(`  repository copilot-instructions.md: ${e.message}`);
    }
  }

  _ensureSetupSteps(projectRoot, log) {
    if (!projectRoot) return;
    const setupPath = join(projectRoot, '.github', 'workflows', 'copilot-setup-steps.yml');
    if (existsSync(setupPath)) {
      log.push('  copilot-setup-steps.yml already exists, skipping');
      return;
    }

    try {
      mkdirSync(dirname(setupPath), { recursive: true });
      writeFileSync(setupPath, this._buildSetupStepsContent(), 'utf-8');
      log.push('  copilot-setup-steps.yml written');
    } catch (e) {
      log.push(`  copilot-setup-steps.yml: ${e.message}`);
    }
  }

  _removeSetupSteps(projectRoot, log) {
    if (!projectRoot) return;
    const setupPath = join(projectRoot, '.github', 'workflows', 'copilot-setup-steps.yml');
    if (!existsSync(setupPath)) return;
    try {
      const content = readFileSync(setupPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  copilot-setup-steps.yml — not generated by loom, skipped');
        return;
      }
      rmSync(setupPath, { force: true });
      log.push('  copilot-setup-steps.yml removed');
    } catch (e) {
      log.push(`  copilot-setup-steps.yml: ${e.message}`);
    }
  }

  _ensureVerificationWorkflow(projectRoot, log) {
    if (!projectRoot) return;
    const workflowPath = join(projectRoot, '.github', 'workflows', 'loom-verify.yml');
    if (existsSync(workflowPath)) {
      log.push('  loom-verify.yml already exists, skipping');
      return;
    }

    try {
      mkdirSync(dirname(workflowPath), { recursive: true });
      writeFileSync(workflowPath, this._buildVerificationWorkflowContent(), 'utf-8');
      log.push('  loom-verify.yml written');
    } catch (e) {
      log.push(`  loom-verify.yml: ${e.message}`);
    }
  }

  _removeVerificationWorkflow(projectRoot, log) {
    if (!projectRoot) return;
    const workflowPath = join(projectRoot, '.github', 'workflows', 'loom-verify.yml');
    if (!existsSync(workflowPath)) return;
    try {
      const content = readFileSync(workflowPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  loom-verify.yml — not generated by loom, skipped');
        return;
      }
      rmSync(workflowPath, { force: true });
      log.push('  loom-verify.yml removed');
    } catch (e) {
      log.push(`  loom-verify.yml: ${e.message}`);
    }
  }

  _removeRepositoryInstructions(projectRoot, log) {
    if (!projectRoot) return;
    const instructionsPath = join(projectRoot, '.github', 'copilot-instructions.md');
    if (!existsSync(instructionsPath)) return;
    try {
      const content = readFileSync(instructionsPath, 'utf-8');
      if (!content.includes('Generated by loom')) {
        log.push('  repository copilot-instructions.md — not generated by loom, skipped');
        return;
      }
      rmSync(instructionsPath, { force: true });
      log.push('  repository copilot-instructions.md removed');
    } catch (e) {
      log.push(`  repository copilot-instructions.md: ${e.message}`);
    }
  }

  _buildSetupStepsContent() {
    return `# Generated by loom
name: Copilot Setup Steps

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Verify generated files
        run: npm run generate:check --if-present
      - name: Run tests
        run: npm test --if-present
`;
  }

  _buildVerificationWorkflowContent() {
    return `# Generated by loom
name: Loom Verify

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Check generated files
        run: npm run generate:check
      - name: Run tests
        run: npm test
      - name: Audit high severity vulnerabilities
        run: npm run audit:high --if-present
      - name: Check documentation consistency
        run: npx vitest run tests/docs-consistency.test.js
`;
  }

  _buildInstructionsContent(loomRoot, version, skillsPath) {
    const skills = this._listSkills(loomRoot).map(s => `- ${s}`).join('\n');
    return `<!-- Generated by loom -->
# Loom — AI 工程化框架 (v${version})

Loom 是 AI 工程化框架

## Skills

以下 skills 已安装到 ${skillsPath}:
${skills}

## 用法

在 Copilot CLI 中, 通过 /skills 命令查看可用 skills。
`;
  }

  _listSkills(loomRoot) {
    const skillsDir = join(loomRoot, 'skills');
    if (!existsSync(skillsDir)) return [];
    return readdirSync(skillsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);
  }
}
