import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdirSync, rmSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CopilotAdapter } from '../../src/adapters/copilot.js';

const TEST_DIR = join(import.meta.dirname, '__test_copilot__');

beforeEach(() => {
  rmSync(TEST_DIR, { recursive: true, force: true, maxRetries: 3, retryDelay: 50 });
  mkdirSync(TEST_DIR, { recursive: true });
});

afterEach(() => {
  vi.restoreAllMocks();
  rmSync(TEST_DIR, { recursive: true, force: true, maxRetries: 3, retryDelay: 50 });
});

describe('CopilotAdapter', () => {
  const adapter = new CopilotAdapter();

  it('has toolName "copilot"', () => {
    expect(adapter.toolName).toBe('copilot');
  });

  it('getUserDir returns ~/.copilot', () => {
    expect(adapter.getUserDir()).toContain('.copilot');
  });

  it('getSkillsDir returns ~/.copilot/skills', () => {
    expect(adapter.getSkillsDir()).toContain(join('.copilot', 'skills'));
  });

  it('getCommandsDir returns ~/.copilot/instructions', () => {
    expect(adapter.getCommandsDir()).toContain(join('.copilot', 'instructions'));
  });

  it('supportsPlugin returns false', () => {
    expect(adapter.supportsPlugin()).toBe(false);
  });

  it('install copies skills and creates copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'test-skill'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'test-skill', 'SKILL.md'), '# Test');

    const log = adapter.install(loomRoot, '1.0.0');
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'test-skill', 'SKILL.md'))).toBe(true);

    const instructionsPath = join(TEST_DIR, '.copilot', 'copilot-instructions.md');
    expect(existsSync(instructionsPath)).toBe(true);
    const content = readFileSync(instructionsPath, 'utf-8');
    expect(content).toContain('Generated by loom');
    expect(content).toContain('1.0.0');
    expect(content).toContain('test-skill');
  });

  it('install creates repository-level copilot instructions', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    const projectRoot = join(TEST_DIR, 'project');
    mkdirSync(join(loomRoot, 'skills', 'test-skill'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'test-skill', 'SKILL.md'), '# Test');

    const log = adapter.install(loomRoot, '1.0.0', projectRoot);

    const instructionsPath = join(projectRoot, '.github', 'copilot-instructions.md');
    expect(existsSync(instructionsPath)).toBe(true);
    const content = readFileSync(instructionsPath, 'utf-8');
    expect(content).toContain('Generated by loom');
    expect(content).toContain('1.0.0');
    expect(content).toContain('test-skill');
    expect(log.some(l => l.includes('repository copilot-instructions.md written'))).toBe(true);
  });

  it('install creates copilot setup steps workflow', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    const projectRoot = join(TEST_DIR, 'project');
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });

    const log = adapter.install(loomRoot, '1.0.0', projectRoot);

    const setupPath = join(projectRoot, '.github', 'workflows', 'copilot-setup-steps.yml');
    expect(existsSync(setupPath)).toBe(true);
    const content = readFileSync(setupPath, 'utf-8');
    expect(content).toContain('Generated by loom');
    expect(content).toContain('actions/setup-node@v4');
    expect(content).toContain('node-version: 22');
    expect(content).toContain('npm run generate:check --if-present');
    expect(content).toContain('npm test --if-present');
    expect(log.some(l => l.includes('copilot-setup-steps.yml written'))).toBe(true);
  });

  it('install skips existing copilot setup steps workflow', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    const projectRoot = join(TEST_DIR, 'project');
    const setupPath = join(projectRoot, '.github', 'workflows', 'copilot-setup-steps.yml');
    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });
    writeFileSync(setupPath, 'name: Custom Setup\n');

    const log = adapter.install(loomRoot, '1.0.0', projectRoot);

    expect(readFileSync(setupPath, 'utf-8')).toBe('name: Custom Setup\n');
    expect(log.some(l => l.includes('copilot-setup-steps.yml already exists'))).toBe(true);
  });

  it('install creates loom verification workflow', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    const projectRoot = join(TEST_DIR, 'project');
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });

    const log = adapter.install(loomRoot, '1.0.0', projectRoot);

    const workflowPath = join(projectRoot, '.github', 'workflows', 'loom-verify.yml');
    expect(existsSync(workflowPath)).toBe(true);
    const content = readFileSync(workflowPath, 'utf-8');
    expect(content).toContain('Generated by loom');
    expect(content).toContain('actions/setup-node@v4');
    expect(content).toContain('npm run generate:check');
    expect(content).toContain('npm test');
    expect(content).toContain('npm run audit:high --if-present');
    expect(content).toContain('npx vitest run tests/docs-consistency.test.js');
    expect(log.some(l => l.includes('loom-verify.yml written'))).toBe(true);
  });

  it('install skips existing loom verification workflow', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    const projectRoot = join(TEST_DIR, 'project');
    const workflowPath = join(projectRoot, '.github', 'workflows', 'loom-verify.yml');
    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });
    writeFileSync(workflowPath, 'name: Custom Verify\n');

    const log = adapter.install(loomRoot, '1.0.0', projectRoot);

    expect(readFileSync(workflowPath, 'utf-8')).toBe('name: Custom Verify\n');
    expect(log.some(l => l.includes('loom-verify.yml already exists'))).toBe(true);
  });

  it('install copies templates to loom-init-project skill dir', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'loom-init-project'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'loom-init-project', 'SKILL.md'), '# Init');
    mkdirSync(join(loomRoot, 'templates'), { recursive: true });
    writeFileSync(join(loomRoot, 'templates', 'constitution.md'), '# Template');

    adapter.install(loomRoot, '1.0.0');

    const templatesDir = join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates');
    expect(existsSync(join(templatesDir, 'constitution.md'))).toBe(true);
  });

  it('install skips templates when loom-init-project not found', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills', 'other-skill'), { recursive: true });
    writeFileSync(join(loomRoot, 'skills', 'other-skill', 'SKILL.md'), '# Other');
    mkdirSync(join(loomRoot, 'templates'), { recursive: true });
    writeFileSync(join(loomRoot, 'templates', 'constitution.md'), '# Template');

    const log = adapter.install(loomRoot, '1.0.0');

    expect(log.some(l => l.includes('not found, skipped'))).toBe(true);
  });

  it('install skips existing copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '# Existing');

    const loomRoot = join(TEST_DIR, 'loom-root');
    mkdirSync(join(loomRoot, 'skills'), { recursive: true });

    const log = adapter.install(loomRoot, '1.0.0');
    expect(log.some(l => l.includes('already exists'))).toBe(true);
    expect(readFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), 'utf-8')).toBe('# Existing');
  });

  it('uninstall removes skills, templates, and loom instructions', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test', 'SKILL.md'), '# Test');
    mkdirSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates', 'test'), 'test');
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '<!-- Generated by loom -->\n# Loom');

    adapter.uninstall(TEST_DIR);

    expect(existsSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'))).toBe(false);
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'loom-test'))).toBe(false);
    expect(existsSync(join(TEST_DIR, '.copilot', 'skills', 'loom-init-project', 'templates'))).toBe(false);
  });

  it('uninstall removes repository-level loom instructions only', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    const projectRoot = join(TEST_DIR, 'project');
    const instructionsPath = join(projectRoot, '.github', 'copilot-instructions.md');
    mkdirSync(join(projectRoot, '.github'), { recursive: true });
    writeFileSync(instructionsPath, '<!-- Generated by loom -->\n# Loom');

    adapter.uninstall(projectRoot);
    expect(existsSync(instructionsPath)).toBe(false);

    mkdirSync(join(projectRoot, '.github'), { recursive: true });
    writeFileSync(instructionsPath, '# My Project Instructions');
    adapter.uninstall(projectRoot);
    expect(existsSync(instructionsPath)).toBe(true);
  });

  it('uninstall removes generated copilot setup steps workflow only', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    const projectRoot = join(TEST_DIR, 'project');
    const setupPath = join(projectRoot, '.github', 'workflows', 'copilot-setup-steps.yml');
    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    writeFileSync(setupPath, '# Generated by loom\nname: Copilot Setup Steps\n');

    adapter.uninstall(projectRoot);
    expect(existsSync(setupPath)).toBe(false);

    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    writeFileSync(setupPath, 'name: Custom Setup\n');
    adapter.uninstall(projectRoot);
    expect(existsSync(setupPath)).toBe(true);
  });

  it('uninstall removes generated loom verification workflow only', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    const projectRoot = join(TEST_DIR, 'project');
    const workflowPath = join(projectRoot, '.github', 'workflows', 'loom-verify.yml');
    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    writeFileSync(workflowPath, '# Generated by loom\nname: Loom Verify\n');

    adapter.uninstall(projectRoot);
    expect(existsSync(workflowPath)).toBe(false);

    mkdirSync(join(projectRoot, '.github', 'workflows'), { recursive: true });
    writeFileSync(workflowPath, 'name: Custom Verify\n');
    adapter.uninstall(projectRoot);
    expect(existsSync(workflowPath)).toBe(true);
  });

  it('uninstall skips non-loom copilot-instructions.md', () => {
    vi.spyOn(adapter, 'getUserDir').mockReturnValue(join(TEST_DIR, '.copilot'));
    mkdirSync(join(TEST_DIR, '.copilot'), { recursive: true });
    writeFileSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'), '# My Custom Instructions');

    adapter.uninstall(TEST_DIR);
    expect(existsSync(join(TEST_DIR, '.copilot', 'copilot-instructions.md'))).toBe(true);
  });
});
