import { describe, it, expect, beforeEach } from 'vitest';
import { mkdtempSync, writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { HANDOFF_STATUSES, PipelineStateStore, scanAllSpecs } from '../../src/core/state-store.js';

function tmp() { return mkdtempSync(join(tmpdir(), 'loom-state-')); }

describe('PipelineStateStore', () => {
  let dir, store;
  beforeEach(() => { dir = tmp(); store = new PipelineStateStore(dir); });

  it('init creates valid pipeline state', () => {
    const s = store.init('feature', '2.0.1');
    expect(s.current_stage).toBe('brainstorming');
    expect(s.pipeline_type).toBe('feature');
    const onDisk = JSON.parse(readFileSync(join(dir, 'pipeline.state.json'), 'utf-8'));
    expect(onDisk.loom_version).toBe('2.0.1');
  });

  it('init creates progress.md immediately', () => {
    store.init('feature', '2.0.1');

    const progress = readFileSync(join(dir, 'progress.md'), 'utf-8');
    expect(progress).toContain('Auto-generated by loom');
    expect(progress).toContain('| Stage | `brainstorming` |');
    expect(progress).toContain('| Type  | `feature` |');
  });

  it('records dynamic steps in progress.md', () => {
    store.init('feature', '2.0.1', 'executing', [
      { id: 'executing' },
      { id: 'verification' }
    ]);

    const progress = readFileSync(join(dir, 'progress.md'), 'utf-8');
    expect(progress).toContain('| Dynamic Steps | executing → verification |');
  });

  it('init is idempotent', () => {
    store.init('feature');
    const again = store.init('bugfix'); // 已存在不应覆盖类型
    expect(again.pipeline_type).toBe('feature');
  });

  it('transition records history and advances stage', () => {
    store.init('feature');
    const s = store.transition('planning');
    expect(s.current_stage).toBe('planning');
    expect(s.stage_history).toHaveLength(1);
    expect(s.stage_history[0].stage).toBe('brainstorming');
    expect(s.stage_history[0].status).toBe('passed');
  });

  it('write leaves valid JSON (atomic, no half-write)', () => {
    store.init('feature');
    store.transition('planning');
    expect(() => JSON.parse(readFileSync(join(dir, 'pipeline.state.json'), 'utf-8'))).not.toThrow();
  });

  it('read throws on corrupt (existing but unparseable) state', () => {
    writeFileSync(join(dir, 'pipeline.state.json'), '{ not json', 'utf-8');
    expect(() => store.read()).toThrow(/Corrupt state file/);
  });

  it('read returns null when state absent', () => {
    expect(store.read()).toBe(null);
  });

  it('updateTask creates task state and readAllTasks sorts numerically', () => {
    store.updateTask('T2', { status: 'done' });
    store.updateTask('T10', { status: 'pending' });
    store.updateTask('T1', { status: 'executing' });
    const tasks = store.readAllTasks();
    expect(tasks.map(t => t.task_id)).toEqual(['T1', 'T2', 'T10']);
  });

  it('rejects unsafe task ids before writing state files', () => {
    expect(() => store.updateTask('../evil', { status: 'done' })).toThrow(/Invalid task id/);
    expect(() => store.updateTask('T1/evil', { status: 'done' })).toThrow(/Invalid task id/);
    expect(existsSync(join(dir, 'evil.state.json'))).toBe(false);
  });

  it('rejects invalid task statuses', () => {
    expect(() => store.updateTask('T1', { status: 'almost-done' })).toThrow(/Invalid task status/);
  });

  it('readAllTasks skips a corrupt task file without throwing', () => {
    store.updateTask('T1', { status: 'done' });
    mkdirSync(join(dir, 'task-states'), { recursive: true });
    writeFileSync(join(dir, 'task-states', 'T2.state.json'), 'garbage', 'utf-8');
    const tasks = store.readAllTasks();
    expect(tasks).toHaveLength(1);
    expect(tasks[0].task_id).toBe('T1');
  });

  it('escapes dynamic markdown fields in progress.md', () => {
    store.init('feature|type');
    store.updateTask('T1', { status: 'blocked', blocker: 'line1\nline|2' });
    store.fail('bad|reason\nnext');

    const progress = readFileSync(join(dir, 'progress.md'), 'utf-8');
    expect(progress).toContain('`feature\\|type`');
    expect(progress).toContain('bad\\|reason<br>next');
    expect(progress).toContain('`T1`');
    expect(progress).toContain('blocked');
    expect(progress).toContain('line1<br>line\\|2');
  });

  it('writes stage handoff and summarizes it in progress.md', () => {
    store.init('feature');
    store.writeStageHandoff('brainstorming', {
      status: 'done',
      summary: '方案已确认|包含换行\n下一步规划',
      artifacts: ['spec.md']
    });

    const handoff = JSON.parse(readFileSync(join(dir, 'handoffs', 'brainstorming.json'), 'utf-8'));
    expect(handoff.stage).toBe('brainstorming');
    expect(handoff.task_id).toBe('brainstorming');

    const progress = readFileSync(join(dir, 'progress.md'), 'utf-8');
    expect(progress).toContain('## Handoffs');
    expect(progress).toContain('| `brainstorming` | done | 方案已确认\\|包含换行<br>下一步规划 | spec.md |');
  });

  it('updates handoff summary incrementally', () => {
    store.init('feature');
    store.writeStageHandoff('planning', {
      status: 'done',
      summary: '初版计划',
      artifacts: ['plan.md']
    });
    store.writeStageHandoff('planning', {
      status: 'done',
      summary: '修订后计划',
      artifacts: ['plan.md', 'tasks/']
    });

    const progress = readFileSync(join(dir, 'progress.md'), 'utf-8');
    expect(progress).toContain('修订后计划');
    expect(progress).not.toContain('初版计划');
    expect(progress).toContain('plan.md, tasks/');
  });

  it('detects a handoff whose compact facts changed after it was written', () => {
    store.init('feature');
    writeFileSync(join(dir, 'spec.md'), '# original spec', 'utf-8');
    store.writeStageHandoff('brainstorming', {
      status: 'done', summary: 'approved', artifacts: ['spec.md']
    });
    expect(store.findStaleHandoffs()).toEqual([]);

    writeFileSync(join(dir, 'spec.md'), '# changed spec', 'utf-8');
    expect(store.findStaleHandoffs()[0]).toMatchObject({
      id: 'brainstorming', changes: expect.arrayContaining([{ path: 'spec.md', reason: 'changed' }])
    });
  });

  it('rejects invalid handoff statuses', () => {
    store.init('feature');
    expect(HANDOFF_STATUSES).toEqual(['done', 'partial', 'blocked', 'failed']);
    expect(() => store.writeStageHandoff('planning', {
      status: 'almost-done',
      summary: 'bad status'
    })).toThrow(/Invalid handoff status/);
    expect(existsSync(join(dir, 'handoffs', 'planning.json'))).toBe(false);
  });
});

describe('scanAllSpecs', () => {
  it('returns specs with pipeline state and tolerates a corrupt one', () => {
    const root = tmp();
    const specsDir = join(root, 'specs');
    const good = join(specsDir, '2026-01-01+good');
    const bad = join(specsDir, '2026-01-02+bad');
    mkdirSync(good, { recursive: true });
    mkdirSync(bad, { recursive: true });
    new PipelineStateStore(good).init('feature');
    writeFileSync(join(bad, 'pipeline.state.json'), 'not json', 'utf-8');
    const all = scanAllSpecs(root);
    expect(all).toHaveLength(1); // 坏的被跳过
    expect(all[0].pipeline.pipeline_type).toBe('feature');
  });
});
